### ISSUE TITLE
Module not found errors when using vite/vinxi and might-fail

### ISSUE THREAD

**Issue by Vakiyama** [meech-ward/might-fail#12]
Steps to reproduce:

1. Start a new solid start project: `bun create solid`
2. Select solid start, basic template, use typescript
3. Import any might fail functions and use in any tsx file

I remember running into this issue in tanstack start as well, which also uses vinxi
I'm unsure if this is a problem with vinxi or with might-fail, but considering no other packages I install give me this issue, I assume 
it's the latter

![image](https://github.com/user-attachments/assets/c9bc18f1-709a-4fd3-bc7a-efa05b1f624c)

**Comment by meech-ward** [comment]
Aparently @iliaamiri has fixed this issue because he's awesome. I'll review the pr and run some tests. In the mean time, jsr doesn't have these issues, so you can use the jsr version:

```bash
bunx jsr add @might/fail
```

```ts
import { mightFail } from "@might/fail"
```

In fact, it might be worth always using the jsr version with bun and deno projects since there's no extra ts compiling as there is with node.

**Comment by meech-ward** [comment]
@Vakiyama This is fixed in version https://github.com/meech-ward/might-fail/releases/tag/0.6.3

**Comment by iliaamiri** [comment]
Thank you Sam!
